/****************************************************************************
 *          g_states.c
 *
 *          Global States
 *
 *          Copyright (c) 2024, ArtGins.
 *          All Rights Reserved.
 ****************************************************************************/
#include "g_states.h"

// Frequent states
GOBJ_DEFINE_STATE(ST_DISCONNECTED);
GOBJ_DEFINE_STATE(ST_WAIT_CONNECTED);
GOBJ_DEFINE_STATE(ST_CONNECTED);
GOBJ_DEFINE_STATE(ST_WAIT_TXED);
GOBJ_DEFINE_STATE(ST_WAIT_DISCONNECTED);
GOBJ_DEFINE_STATE(ST_WAIT_STOPPED);
GOBJ_DEFINE_STATE(ST_WAIT_HANDSHAKE);
GOBJ_DEFINE_STATE(ST_WAIT_IMEI);
GOBJ_DEFINE_STATE(ST_WAIT_ID);
GOBJ_DEFINE_STATE(ST_STOPPED);
GOBJ_DEFINE_STATE(ST_SESSION);
GOBJ_DEFINE_STATE(ST_IDLE);
GOBJ_DEFINE_STATE(ST_WAIT_RESPONSE);
GOBJ_DEFINE_STATE(ST_OPENED);
GOBJ_DEFINE_STATE(ST_CLOSED);
GOBJ_DEFINE_STATE(ST_DISABLED);

GOBJ_DEFINE_STATE(ST_WAITING_HANDSHAKE);
GOBJ_DEFINE_STATE(ST_WAITING_FRAME_HEADER);
GOBJ_DEFINE_STATE(ST_WAITING_PAYLOAD_DATA);
