/****************************************************************************
 *          g_ev_console.h
 *
 *          Global Events of Console
 *
 *          Copyright (c) 2024, ArtGins.
 *          All Rights Reserved.
 ****************************************************************************/
#pragma once

#include "gobj.h"

#ifdef __cplusplus
extern "C"{
#endif

GOBJ_DECLARE_EVENT(EV_COMMAND);
GOBJ_DECLARE_EVENT(EV_KEYCHAR);
GOBJ_DECLARE_EVENT(EV_EDITLINE_MOVE_START);
GOBJ_DECLARE_EVENT(EV_EDITLINE_MOVE_LEFT);
GOBJ_DECLARE_EVENT(EV_EDITLINE_DEL_CHAR);
GOBJ_DECLARE_EVENT(EV_EDITLINE_MOVE_END);
GOBJ_DECLARE_EVENT(EV_EDITLINE_MOVE_RIGHT);
GOBJ_DECLARE_EVENT(EV_EDITLINE_BACKSPACE);
GOBJ_DECLARE_EVENT(EV_EDITLINE_COMPLETE_LINE);
GOBJ_DECLARE_EVENT(EV_EDITLINE_DEL_EOL);
GOBJ_DECLARE_EVENT(EV_EDITLINE_ENTER);
GOBJ_DECLARE_EVENT(EV_EDITLINE_PREV_HIST);
GOBJ_DECLARE_EVENT(EV_EDITLINE_NEXT_HIST);
GOBJ_DECLARE_EVENT(EV_EDITLINE_SWAP_CHAR);
GOBJ_DECLARE_EVENT(EV_EDITLINE_DEL_LINE);
GOBJ_DECLARE_EVENT(EV_EDITLINE_DEL_PREV_WORD);
GOBJ_DECLARE_EVENT(EV_GETTEXT); // HACK EV_GETTEXT is EVF_KW_WRITING
GOBJ_DECLARE_EVENT(EV_SETTEXT);
GOBJ_DECLARE_EVENT(EV_SIZE);
GOBJ_DECLARE_EVENT(EV_MOVE);
GOBJ_DECLARE_EVENT(EV_PAINT);
GOBJ_DECLARE_EVENT(EV_SCREEN_SIZE_CHANGE);
GOBJ_DECLARE_EVENT(EV_SETFOCUS);
GOBJ_DECLARE_EVENT(EV_KILLFOCUS);
GOBJ_DECLARE_EVENT(EV_SET_TOP_WINDOW);
GOBJ_DECLARE_EVENT(EV_CLEAR_HISTORY);
GOBJ_DECLARE_EVENT(EV_CLRSCR);
GOBJ_DECLARE_EVENT(EV_SCROLL_PAGE_UP);
GOBJ_DECLARE_EVENT(EV_SCROLL_PAGE_DOWN);
GOBJ_DECLARE_EVENT(EV_SCROLL_LINE_UP);
GOBJ_DECLARE_EVENT(EV_SCROLL_LINE_DOWN);
GOBJ_DECLARE_EVENT(EV_SCROLL_TOP);
GOBJ_DECLARE_EVENT(EV_SCROLL_BOTTOM);
GOBJ_DECLARE_EVENT(EV_SET_SELECTED_BUTTON);
GOBJ_DECLARE_EVENT(EV_GET_PREV_SELECTED_BUTTON);
GOBJ_DECLARE_EVENT(EV_GET_NEXT_SELECTED_BUTTON);

GOBJ_DECLARE_EVENT(EV_QUIT);
GOBJ_DECLARE_EVENT(EV_PREVIOUS_WINDOW);
GOBJ_DECLARE_EVENT(EV_NEXT_WINDOW);
GOBJ_DECLARE_EVENT(EV_EDIT_CONFIG);
GOBJ_DECLARE_EVENT(EV_VIEW_CONFIG);
GOBJ_DECLARE_EVENT(EV_EDIT_YUNO_CONFIG);
GOBJ_DECLARE_EVENT(EV_VIEW_YUNO_CONFIG);
GOBJ_DECLARE_EVENT(EV_READ_JSON);
GOBJ_DECLARE_EVENT(EV_READ_FILE);
GOBJ_DECLARE_EVENT(EV_READ_BINARY_FILE);
GOBJ_DECLARE_EVENT(EV_TTY_OPEN);
GOBJ_DECLARE_EVENT(EV_TTY_CLOSE);
GOBJ_DECLARE_EVENT(EV_TTY_DATA);
GOBJ_DECLARE_EVENT(EV_WRITE_TTY);

#ifdef __cplusplus
}
#endif
