/****************************************************************************
 *          g_ev_console.c
 *
 *          Global Events of Console
  *
 *          Copyright (c) 2024, ArtGins.
 *          All Rights Reserved.
 ****************************************************************************/
#include "g_ev_console.h"

GOBJ_DEFINE_EVENT(EV_COMMAND);
GOBJ_DEFINE_EVENT(EV_KEYCHAR);
GOBJ_DEFINE_EVENT(EV_MOUSE);
GOBJ_DEFINE_EVENT(EV_EDITLINE_MOVE_START);
GOBJ_DEFINE_EVENT(EV_EDITLINE_MOVE_LEFT);
GOBJ_DEFINE_EVENT(EV_EDITLINE_DEL_CHAR);
GOBJ_DEFINE_EVENT(EV_EDITLINE_MOVE_END);
GOBJ_DEFINE_EVENT(EV_EDITLINE_MOVE_RIGHT);
GOBJ_DEFINE_EVENT(EV_EDITLINE_BACKSPACE);
GOBJ_DEFINE_EVENT(EV_EDITLINE_COMPLETE_LINE);
GOBJ_DEFINE_EVENT(EV_EDITLINE_DEL_EOL);
GOBJ_DEFINE_EVENT(EV_EDITLINE_ENTER);
GOBJ_DEFINE_EVENT(EV_EDITLINE_PREV_HIST);
GOBJ_DEFINE_EVENT(EV_EDITLINE_NEXT_HIST);
GOBJ_DEFINE_EVENT(EV_EDITLINE_SWAP_CHAR);
GOBJ_DEFINE_EVENT(EV_EDITLINE_DEL_LINE);
GOBJ_DEFINE_EVENT(EV_EDITLINE_DEL_PREV_WORD);
GOBJ_DEFINE_EVENT(EV_GETTEXT);  // HACK EV_GETTEXT is EVF_KW_WRITING
GOBJ_DEFINE_EVENT(EV_SETTEXT);
GOBJ_DEFINE_EVENT(EV_SIZE);
GOBJ_DEFINE_EVENT(EV_MOVE);
GOBJ_DEFINE_EVENT(EV_PAINT);
GOBJ_DEFINE_EVENT(EV_SCREEN_SIZE_CHANGE);
GOBJ_DEFINE_EVENT(EV_SETFOCUS);
GOBJ_DEFINE_EVENT(EV_KILLFOCUS);
GOBJ_DEFINE_EVENT(EV_SET_TOP_WINDOW);
GOBJ_DEFINE_EVENT(EV_CLEAR_HISTORY);
GOBJ_DEFINE_EVENT(EV_CLRSCR);
GOBJ_DEFINE_EVENT(EV_SCROLL_PAGE_UP);
GOBJ_DEFINE_EVENT(EV_SCROLL_PAGE_DOWN);
GOBJ_DEFINE_EVENT(EV_SCROLL_LINE_UP);
GOBJ_DEFINE_EVENT(EV_SCROLL_LINE_DOWN);
GOBJ_DEFINE_EVENT(EV_SCROLL_TOP);
GOBJ_DEFINE_EVENT(EV_SCROLL_BOTTOM);
GOBJ_DEFINE_EVENT(EV_SET_SELECTED_BUTTON);
GOBJ_DEFINE_EVENT(EV_GET_PREV_SELECTED_BUTTON);
GOBJ_DEFINE_EVENT(EV_GET_NEXT_SELECTED_BUTTON);

GOBJ_DEFINE_EVENT(EV_QUIT);
GOBJ_DEFINE_EVENT(EV_PREVIOUS_WINDOW);
GOBJ_DEFINE_EVENT(EV_NEXT_WINDOW);
