/****************************************************************************
 *          g_events.c
 *
 *          Global Events
 *
 *          Copyright (c) 2024, ArtGins.
 *          All Rights Reserved.
 ****************************************************************************/
#include "g_events.h"

// Timer Events, defined here to easy filtering in trace
GOBJ_DEFINE_EVENT(EV_TIMEOUT);
GOBJ_DEFINE_EVENT(EV_TIMEOUT_PERIODIC);

// System Events
GOBJ_DEFINE_EVENT(EV_STATE_CHANGED);

// Channel Messages: Input Events (Requests)
GOBJ_DEFINE_EVENT(EV_SEND_MESSAGE);
GOBJ_DEFINE_EVENT(EV_SEND_IEV);
GOBJ_DEFINE_EVENT(EV_SEND_EMAIL);
GOBJ_DEFINE_EVENT(EV_DROP);
GOBJ_DEFINE_EVENT(EV_REMOTE_LOG);
GOBJ_DEFINE_EVENT(EV_SEND_ENCRYPTED_DATA);

// Channel Messages: Output Events (Publications)
GOBJ_DEFINE_EVENT(EV_ON_OPEN);
GOBJ_DEFINE_EVENT(EV_ON_CLOSE);
GOBJ_DEFINE_EVENT(EV_ON_MESSAGE);      // with GBuffer
GOBJ_DEFINE_EVENT(EV_ON_COMMAND);
GOBJ_DEFINE_EVENT(EV_ON_IEV_MESSAGE);  // with IEvent, old EV_IEV_MESSAGE
GOBJ_DEFINE_EVENT(EV_ON_ID);
GOBJ_DEFINE_EVENT(EV_ON_ID_NAK);
GOBJ_DEFINE_EVENT(EV_ON_HEADER);

GOBJ_DEFINE_EVENT(EV_HTTP_MESSAGE);

// Tube Messages
GOBJ_DEFINE_EVENT(EV_CONNECT);
GOBJ_DEFINE_EVENT(EV_CONNECTED);
GOBJ_DEFINE_EVENT(EV_DISCONNECT);
GOBJ_DEFINE_EVENT(EV_DISCONNECTED);
GOBJ_DEFINE_EVENT(EV_RX_DATA);
GOBJ_DEFINE_EVENT(EV_TX_DATA);
GOBJ_DEFINE_EVENT(EV_TX_READY);
GOBJ_DEFINE_EVENT(EV_STOPPED);

// CLI Messages
GOBJ_DEFINE_EVENT(EV_COMMAND);
GOBJ_DEFINE_EVENT(EV_KEYCHAR);
GOBJ_DEFINE_EVENT(EV_EDITLINE_MOVE_START);
GOBJ_DEFINE_EVENT(EV_EDITLINE_MOVE_LEFT);
GOBJ_DEFINE_EVENT(EV_EDITLINE_DEL_CHAR);
GOBJ_DEFINE_EVENT(EV_EDITLINE_MOVE_END);
GOBJ_DEFINE_EVENT(EV_EDITLINE_MOVE_RIGHT);
GOBJ_DEFINE_EVENT(EV_EDITLINE_BACKSPACE);
GOBJ_DEFINE_EVENT(EV_EDITLINE_COMPLETE_LINE);
GOBJ_DEFINE_EVENT(EV_EDITLINE_DEL_EOL);
GOBJ_DEFINE_EVENT(EV_EDITLINE_ENTER);
GOBJ_DEFINE_EVENT(EV_EDITLINE_PREV_HIST);
GOBJ_DEFINE_EVENT(EV_EDITLINE_NEXT_HIST);
GOBJ_DEFINE_EVENT(EV_EDITLINE_SWAP_CHAR);
GOBJ_DEFINE_EVENT(EV_EDITLINE_DEL_LINE);
GOBJ_DEFINE_EVENT(EV_EDITLINE_DEL_PREV_WORD);
GOBJ_DEFINE_EVENT(EV_GETTEXT);
GOBJ_DEFINE_EVENT(EV_SETTEXT);
GOBJ_DEFINE_EVENT(EV_SIZE);
GOBJ_DEFINE_EVENT(EV_MOVE);
GOBJ_DEFINE_EVENT(EV_PAINT);
GOBJ_DEFINE_EVENT(EV_SCREEN_SIZE_CHANGE);
GOBJ_DEFINE_EVENT(EV_SETFOCUS);
GOBJ_DEFINE_EVENT(EV_KILLFOCUS);
GOBJ_DEFINE_EVENT(EV_SET_TOP_WINDOW);
GOBJ_DEFINE_EVENT(EV_REFRESH_LINE);
GOBJ_DEFINE_EVENT(EV_CLEAR_HISTORY);
GOBJ_DEFINE_EVENT(EV_CLRSCR);
GOBJ_DEFINE_EVENT(EV_SCROLL_PAGE_UP);
GOBJ_DEFINE_EVENT(EV_SCROLL_PAGE_DOWN);
GOBJ_DEFINE_EVENT(EV_SCROLL_LINE_UP);
GOBJ_DEFINE_EVENT(EV_SCROLL_LINE_DOWN);
GOBJ_DEFINE_EVENT(EV_SCROLL_TOP);
GOBJ_DEFINE_EVENT(EV_SCROLL_BOTTOM);

GOBJ_DEFINE_EVENT(EV_QUIT);
GOBJ_DEFINE_EVENT(EV_PREVIOUS_WINDOW);
GOBJ_DEFINE_EVENT(EV_NEXT_WINDOW);
GOBJ_DEFINE_EVENT(EV_EDIT_CONFIG);
GOBJ_DEFINE_EVENT(EV_VIEW_CONFIG);
GOBJ_DEFINE_EVENT(EV_EDIT_YUNO_CONFIG);
GOBJ_DEFINE_EVENT(EV_VIEW_YUNO_CONFIG);
GOBJ_DEFINE_EVENT(EV_READ_JSON);
GOBJ_DEFINE_EVENT(EV_READ_FILE);
GOBJ_DEFINE_EVENT(EV_READ_BINARY_FILE);
GOBJ_DEFINE_EVENT(EV_TTY_OPEN);
GOBJ_DEFINE_EVENT(EV_TTY_CLOSE);
GOBJ_DEFINE_EVENT(EV_TTY_DATA);
GOBJ_DEFINE_EVENT(EV_WRITE_TTY);
